### PR TITLE
Quadratic formula code check before md, made it simple

### PR DESCRIPTION
**Pull request by MusaMoses**
Uh I just want to you to check it if its good enough as an example for the beginners?

### CODE REVIEW

**Review by Zenoix — CHANGES_REQUESTED** [review]
There are I few issues that I have found (there may be more but this is just from a quick scan):

- Docstring at the top of the program would be helpful
- Maybe use more functions like a receive input function, calculate discriminant function etc.
- A quadratic equation is allowed to have the `a` coefficient less than 1. The only exception being when `a == 0` because then the equation is dividing by 0.
- It is possible for the discriminant to be less than zero when the roots are on the complex plane. Maybe look at a way to implement complex solutions by default or maybe as an option for the user.
- I think the formatting is a bit off but maybe that's just my opinion??
- There are a few spelling errors like in line 10 and `discriminant` is misspelt throughout.
- The final outputs of the roots should only be the two roots like `x1 = ... and x2 = ...` or something equivalent, not `(x1, 0) and (x2, 0)`
- Follow pep8

Sorry if I'm a bit harsh 😄

**Comment by MusaMoses** [comment]
Haha no problem Its making for functions would just break down the code allowing the code to look neater im which can be done, as well as it interesting that you say the final outputs of the roots should only be x1 = and x2 = because i was taught that the roots are the x intercepts and you would say that they are (x1, 0) (x2, 0) but sure.

**Comment by MusaMoses** [comment]
Schools is starting soon tho however I can finish it after :)

**Comment by MusaMoses** [comment]
I have also never touched upon complex roots so ill look into that.

**Comment by MusaMoses** [comment]
All I need is confirmation its what you want so I can write the md .

**Review by ZechCodes — COMMENTED** [review]
Weather checker looks good. Gonna let @Zenoix review the quadratic formula solver as they're more familiar with the math.

**Review by Zenoix — CHANGES_REQUESTED** [review]
I like how you used `cmath` for the complex roots but it could also be done without it (might just want to explain that in the md). 

A few things:
- Spelling mistakes - discriminant is misspelt through the whole code, line 12 function name is incorrectly spelt, line 55 etc. Check spelling is perfect if you want to use the code as an example for others.
- In your multiline comments you use the word polynomial which a quadratic is, however, using the term polynomial in for example line 24 implies that the quadratic equation will work for any polynomial which it won't. Consider changing polynomial into quadratic
- Multiline comments are inconsistently formatted
- `discriminant` function, the equation is a bit off. `return b ** 2 - 4 * a * c`. Unessacery outer brackets and the it is b^2 not (-b)^2 although they are the same. 
- Is there a reason that the `Discriminant` variable isn't all lowercase?
- `quadratic_formula()` function can be refactored a bit and is it possible to round the complex roots? 
- In main function, you should first print to the user the form you expect the quadratic to be in (`ax^2+bx+c = 0`) before asking for the coefficients.

Good work though! Nearly there :)

**Comment by MusaMoses** [comment]
I can do everything else for you after class but I am unsure of how to do complex roots without cmath because i was never taught it. I tried to look at how it is solved for, however they used alot of algebra and Im unsure of how to make my code do algebra too, if it was simply an expression or order of operations I could have done it myself.

I am also geuinly intrested how you can do it so i would like you to recommend me  a vid on it one more time, any ill try to take it on.

:)
Thanks
This is a fun experience on github you guys are the best for allowing me to contribute.

**Review by Zenoix — CHANGES_REQUESTED** [review]
You don't have to change the cmath part. I was just telling you that you didn't have to which is probably something you should explain in the solution walkthrough in case the reader doesn't want to get into cmath.

One last thing that I can see, I think the `format_equation()` function should be above the `quadratic_calculator()` function as the `quadratic_calculator()` calls the `format_equation()`. Make sure the file is formatted properly by a linter/formatter and then I'll merge it :)

**Comment by MusaMoses** [comment]
Everything looks good wang you can recheck once more and ill work on the explanation of it

**Review by Zenoix — APPROVED** [review]
Looks good!

**Pull request merged**
